export const COURSE_COMMENTS = {
  "1": { comments: 24, reviews: 8, avgRating: 4.9, flagged: 3, hidden: 1, deleted: 0 },
  "2": { comments: 18, reviews: 6, avgRating: 4.8, flagged: 1, hidden: 0, deleted: 1 },
  "3": { comments: 45, reviews: 14, avgRating: 4.7, flagged: 7, hidden: 3, deleted: 2 },
  "4": { comments: 5, reviews: 2, avgRating: 4.6, flagged: 0, hidden: 0, deleted: 0 },
  "5": { comments: 0, reviews: 0, avgRating: 0, flagged: 0, hidden: 0, deleted: 0 },
};

export type ModerationItem = {
  id: string;
  type: "comment" | "review" | "rating";
  author: string;
  content: string;
  course: string;
  date: string;
  reported: boolean;
  hidden: boolean;
  rating?: number;
  edited?: boolean;
};

export const MODERATION_ITEMS: ModerationItem[] = [
  {
    id: "m1",
    type: "comment",
    author: "John D.",
    content: "This module is confusing — the instructor skipped important steps.",
    course: "AI & ML for Business Leaders",
    date: "2h ago",
    reported: true,
    hidden: false,
  },
  {
    id: "m2",
    type: "review",
    author: "Anonymous",
    content: "Terrible course, total waste of time.",
    course: "AI & ML for Business Leaders",
    date: "1 day ago",
    reported: true,
    hidden: false,
    rating: 1,
  },
  {
    id: "m3",
    type: "comment",
    author: "User_4521",
    content: "Can anyone share the quiz answers?",
    course: "AI & ML for Business Leaders",
    date: "3 days ago",
    reported: true,
    hidden: false,
  },
  {
    id: "m4",
    type: "review",
    author: "Learner99",
    content: "Below expectations.",
    course: "AI & ML for Business Leaders",
    date: "4 days ago",
    reported: false,
    hidden: true,
    rating: 2,
  },
  {
    id: "m5",
    type: "comment",
    author: "TechUser",
    content: "Great session, really appreciated the deep dive on neural networks!",
    course: "AI & ML for Business Leaders",
    date: "5 days ago",
    reported: false,
    hidden: false,
  },
  {
    id: "m6",
    type: "rating",
    author: "Anonymous",
    content: "1-star no comment",
    course: "AI & ML for Business Leaders",
    date: "6 days ago",
    reported: false,
    hidden: false,
    rating: 1,
  },
  {
    id: "m7",
    type: "comment",
    author: "Mariam T.",
    content:
      "The dashboard exercise was useful, but the final case study needs clearer data labels.",
    course: "Data-Driven Leadership",
    date: "4h ago",
    reported: false,
    hidden: false,
  },
  {
    id: "m8",
    type: "review",
    author: "Operations Lead",
    content: "Strong course. I would add more examples from telecom operations.",
    course: "Data-Driven Leadership",
    date: "1 day ago",
    reported: false,
    hidden: false,
    rating: 4,
  },
  {
    id: "m9",
    type: "comment",
    author: "Anonymous",
    content: "The assignment link is broken in module 3.",
    course: "Data-Driven Leadership",
    date: "2 days ago",
    reported: true,
    hidden: false,
  },
  {
    id: "m10",
    type: "comment",
    author: "SecurityLearner",
    content: "Please add the password policy PDF mentioned in the video.",
    course: "Cybersecurity Fundamentals",
    date: "3h ago",
    reported: false,
    hidden: false,
  },
  {
    id: "m11",
    type: "review",
    author: "Anonymous",
    content: "Too much terminology in the first chapter. It should start with a glossary.",
    course: "Cybersecurity Fundamentals",
    date: "7h ago",
    reported: true,
    hidden: false,
    rating: 2,
  },
  {
    id: "m12",
    type: "comment",
    author: "User_3108",
    content: "Can someone send me the assessment answers before the deadline?",
    course: "Cybersecurity Fundamentals",
    date: "1 day ago",
    reported: true,
    hidden: false,
  },
  {
    id: "m13",
    type: "review",
    author: "Mei Lin",
    content: "Practical and easy to follow. The phishing examples were excellent.",
    course: "Cybersecurity Fundamentals",
    date: "3 days ago",
    reported: false,
    hidden: false,
    rating: 5,
  },
  {
    id: "m14",
    type: "comment",
    author: "Sam K.",
    content: "The role-play activity helped me understand active listening better.",
    course: "Effective Communication",
    date: "5h ago",
    reported: false,
    hidden: false,
  },
  {
    id: "m15",
    type: "review",
    author: "HR Partner",
    content: "Good starter course. The tone is friendly and the exercises are short enough.",
    course: "Effective Communication",
    date: "2 days ago",
    reported: false,
    hidden: false,
    rating: 4,
  },
];
