import type { Course } from "../models/app.model";
import { P } from "./theme.constants";

export const COURSES: Course[] = [
  {
    id: "1",
    title: "AI & Machine Learning for Business Leaders",
    category: "Technology",
    level: "Intermediate",
    duration: "8h 30m",
    lessons: 42,
    rating: 4.9,
    enrolled: 12840,
    progress: 65,
    isEnrolled: true,
    color: P.olive,
    instructor: "Dr. Sarah Chen",
    instructorAvatar: "SC",
    tags: ["AI", "Strategy"],
    recommended: true,
    mandatory: false,
    thumbnail:
      "https://images.unsplash.com/photo-1674027444485-cec3da58eef4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "2",
    title: "Data-Driven Leadership & Decision Making",
    category: "Leadership",
    level: "Advanced",
    duration: "6h 15m",
    lessons: 31,
    rating: 4.8,
    enrolled: 9320,
    progress: 28,
    isEnrolled: true,
    color: P.darkOlive,
    instructor: "Marcus Johnson",
    instructorAvatar: "MJ",
    tags: ["Analytics", "Leadership"],
    recommended: true,
    mandatory: false,
    thumbnail:
      "https://images.unsplash.com/photo-1666875753105-c63a6f3bdc86?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "3",
    title: "Cybersecurity Fundamentals & Compliance",
    category: "Compliance",
    level: "Beginner",
    duration: "4h 00m",
    lessons: 20,
    rating: 4.7,
    enrolled: 24100,
    progress: 100,
    isEnrolled: true,
    color: "#C0392B",
    instructor: "Priya Sharma",
    instructorAvatar: "PS",
    tags: ["Security", "Compliance"],
    recommended: false,
    mandatory: true,
    thumbnail:
      "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "4",
    title: "Effective Communication in Remote Teams",
    category: "Soft Skills",
    level: "Beginner",
    duration: "3h 45m",
    lessons: 18,
    rating: 4.6,
    enrolled: 18200,
    progress: 0,
    isEnrolled: true,
    color: P.sage,
    instructor: "James Okafor",
    instructorAvatar: "JO",
    tags: ["Communication"],
    recommended: true,
    mandatory: false,
    thumbnail:
      "https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "5",
    title: "Financial Modeling & Business Valuation",
    category: "Finance",
    level: "Advanced",
    duration: "12h 00m",
    lessons: 58,
    rating: 4.8,
    enrolled: 6700,
    progress: 0,
    isEnrolled: false,
    color: P.gold,
    instructor: "Sofia Andersen",
    instructorAvatar: "SA",
    tags: ["Finance", "Excel"],
    recommended: false,
    mandatory: false,
    thumbnail:
      "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "6",
    title: "Design Thinking & Innovation Workshop",
    category: "Design",
    level: "Intermediate",
    duration: "5h 20m",
    lessons: 24,
    rating: 4.7,
    enrolled: 8900,
    progress: 0,
    isEnrolled: false,
    color: "#8B6914",
    instructor: "Lena Mueller",
    instructorAvatar: "LM",
    tags: ["UX", "Innovation"],
    recommended: true,
    mandatory: false,
    preCourseAssessment: "disabled",
    thumbnail:
      "https://images.unsplash.com/photo-1587440871875-191322ee64b0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "7",
    title: "Project Management: Agile & Scrum Mastery",
    category: "Management",
    level: "Intermediate",
    duration: "9h 10m",
    lessons: 45,
    rating: 4.9,
    enrolled: 15400,
    progress: 0,
    isEnrolled: true,
    color: "#4A7A5A",
    instructor: "Ravi Patel",
    instructorAvatar: "RP",
    tags: ["Agile", "Scrum"],
    recommended: false,
    mandatory: false,
    thumbnail:
      "https://images.unsplash.com/photo-1557804506-669a67965ba0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "8",
    title: "ESG & Sustainability in Corporate Strategy",
    category: "Leadership",
    level: "Intermediate",
    duration: "4h 30m",
    lessons: 22,
    rating: 4.5,
    enrolled: 5600,
    progress: 0,
    isEnrolled: false,
    color: P.darkOlive,
    instructor: "Emma Williams",
    instructorAvatar: "EW",
    tags: ["ESG", "Strategy"],
    recommended: false,
    mandatory: true,
    preCourseAssessment: "mandatory",
    thumbnail:
      "https://images.unsplash.com/photo-1597150899069-efb9c8c6010c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "aws-cloud-practitioner",
    title: "AWS Cloud Practitioner Certification Prep",
    category: "Technology",
    level: "Beginner",
    duration: "10h 15m",
    lessons: 36,
    rating: 4.8,
    enrolled: 48,
    progress: 0,
    isEnrolled: false,
    color: "#D4922F",
    instructor: "Amazon Web Services",
    instructorAvatar: "AWS",
    tags: ["Cloud", "Certification"],
    recommended: true,
    mandatory: false,
    provider: "Amazon Web Services",
    providerShort: "AWS",
    providerStatus: "Integrated",
    providerCredential: "Cloud Practitioner",
    thumbnail:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "gcp-digital-leader",
    title: "Google Cloud Digital Leader Certification Prep",
    category: "Technology",
    level: "Beginner",
    duration: "8h 45m",
    lessons: 28,
    rating: 4.7,
    enrolled: 31,
    progress: 0,
    isEnrolled: false,
    color: "#2F7DE1",
    instructor: "Google Cloud",
    instructorAvatar: "GC",
    tags: ["Cloud", "Data"],
    recommended: true,
    mandatory: false,
    provider: "Google Cloud",
    providerShort: "GCP",
    providerStatus: "Integrated",
    providerCredential: "Cloud Digital Leader",
    thumbnail:
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "pmi-pmp-foundations",
    title: "PMI PMP Foundations & Exam Readiness",
    category: "Management",
    level: "Advanced",
    duration: "14h 00m",
    lessons: 52,
    rating: 4.8,
    enrolled: 18,
    progress: 0,
    isEnrolled: false,
    color: P.gold,
    instructor: "PMI",
    instructorAvatar: "PMI",
    tags: ["PMP", "Project Management"],
    recommended: false,
    mandatory: false,
    provider: "PMI",
    providerShort: "PMI",
    providerStatus: "Manual",
    providerCredential: "PMP",
    preCourseAssessment: "optional",
    thumbnail:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "comptia-security-plus",
    title: "CompTIA Security+ Certification Prep",
    category: "Compliance",
    level: "Intermediate",
    duration: "11h 30m",
    lessons: 44,
    rating: 4.9,
    enrolled: 62,
    progress: 0,
    isEnrolled: false,
    color: "#4A7A5A",
    instructor: "CompTIA",
    instructorAvatar: "CT",
    tags: ["Security+", "Network"],
    recommended: true,
    mandatory: false,
    provider: "CompTIA",
    providerShort: "CompTIA",
    providerStatus: "Integrated",
    providerCredential: "Security+",
    thumbnail:
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
  {
    id: "microsoft-azure-fundamentals",
    title: "Microsoft Azure Fundamentals Certification Prep",
    category: "Technology",
    level: "Beginner",
    duration: "9h 20m",
    lessons: 34,
    rating: 4.7,
    enrolled: 74,
    progress: 0,
    isEnrolled: false,
    color: "#3478B8",
    instructor: "Microsoft",
    instructorAvatar: "MS",
    tags: ["Azure", "Power BI"],
    recommended: false,
    mandatory: false,
    provider: "Microsoft",
    providerShort: "MSFT",
    providerStatus: "Integrated",
    providerCredential: "Azure Fundamentals",
    thumbnail:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=400",
  },
];

export const PROGRAMS = [
  {
    id: "pg1",
    title: "ADIU Onboarding Program",
    description:
      "A structured 6-week program to help new employees ramp up, meet their team, and hit the ground running",
    courses: 6,
    duration: "6 weeks",
    enrolled: 42,
    progress: 65,
    color: P.olive,
    badge: "🌿",
    skills: ["Company Culture", "Role Readiness", "Communication"],
  },
  {
    id: "pg2",
    title: "Future Leaders Initiative",
    description:
      "Develop the leadership mindset and skills needed to drive teams and strategy at ADIU Communication Service PLC",
    courses: 8,
    duration: "12 weeks",
    enrolled: 15,
    progress: 38,
    color: P.gold,
    badge: "🏅",
    skills: ["Strategic Thinking", "Digital Fluency", "Change Management"],
  },
  {
    id: "pg3",
    title: "2025 Regulatory Compliance Pack",
    description:
      "Mandatory program covering all regulatory and compliance requirements — required for all ADIU employees",
    courses: 5,
    duration: "4 weeks",
    enrolled: 1247,
    progress: 72,
    color: "#C0392B",
    badge: "🛡️",
    skills: ["Risk Management", "Regulatory Compliance", "Ethics"],
  },
  {
    id: "pg4",
    title: "Engineering Excellence Track",
    description:
      "A deep-dive technical program for engineers to advance their skills across architecture, security, and delivery",
    courses: 9,
    duration: "16 weeks",
    enrolled: 78,
    progress: 44,
    color: P.darkOlive,
    badge: "⚙️",
    skills: ["System Design", "DevOps", "Code Quality"],
  },
  {
    id: "pg5",
    title: "Graduate Talent Program",
    description:
      "A 24-week immersive program for new graduate hires to rotate across functions and build a strong foundation",
    courses: 12,
    duration: "24 weeks",
    enrolled: 28,
    progress: 18,
    color: "#4A7A5A",
    badge: "🌱",
    skills: ["Business Acumen", "People Management", "Coaching"],
  },
];

export const LEADERBOARD_DATA = [
  {
    rank: 1,
    name: "Aisha Rahman",
    dept: "Engineering",
    xp: 14820,
    courses: 28,
    badges: 12,
    avatar: "AR",
    trend: "up",
  },
  {
    rank: 2,
    name: "Carlos Mendez",
    dept: "Product",
    xp: 13640,
    courses: 25,
    badges: 10,
    avatar: "CM",
    trend: "up",
  },
  {
    rank: 3,
    name: "Yuki Tanaka",
    dept: "Design",
    xp: 12910,
    courses: 24,
    badges: 11,
    avatar: "YT",
    trend: "same",
  },
  {
    rank: 4,
    name: "Alex Mercer",
    dept: "Engineering",
    xp: 11250,
    courses: 21,
    badges: 9,
    avatar: "AM",
    trend: "up",
    isMe: true,
  },
  {
    rank: 5,
    name: "Fatima Al-Hassan",
    dept: "Finance",
    xp: 10800,
    courses: 20,
    badges: 8,
    avatar: "FA",
    trend: "down",
  },
  {
    rank: 6,
    name: "Ben Ostrowski",
    dept: "HR",
    xp: 9940,
    courses: 19,
    badges: 7,
    avatar: "BO",
    trend: "up",
  },
  {
    rank: 7,
    name: "Priya Nair",
    dept: "Marketing",
    xp: 9210,
    courses: 17,
    badges: 7,
    avatar: "PN",
    trend: "down",
  },
  {
    rank: 8,
    name: "Luca Ferrari",
    dept: "Sales",
    xp: 8670,
    courses: 16,
    badges: 6,
    avatar: "LF",
    trend: "same",
  },
  {
    rank: 9,
    name: "Mei Lin",
    dept: "Operations",
    xp: 8120,
    courses: 15,
    badges: 6,
    avatar: "ML",
    trend: "up",
  },
  {
    rank: 10,
    name: "Thomas Gruber",
    dept: "Legal",
    xp: 7890,
    courses: 15,
    badges: 5,
    avatar: "TG",
    trend: "down",
  },
];

export const NOTIFICATIONS = [
  {
    id: "n1",
    type: "reminder",
    title: "Course deadline approaching",
    body: '"AI & ML for Business Leaders" is due in 3 days. You\'re 65% complete.',
    time: "5 min ago",
    read: false,
    icon: "clock",
  },
  {
    id: "n2",
    type: "achievement",
    title: "🏆 Badge Earned: Data Trailblazer",
    body: "You've completed 5 courses in the Data & Analytics category!",
    time: "2 hours ago",
    read: false,
    icon: "trophy",
  },
  {
    id: "n3",
    type: "ai",
    title: "🤖 AI Learning Insight",
    body: "Based on your role and recent activity, we recommend starting 'Data-Driven Leadership' next week.",
    time: "1 day ago",
    read: false,
    icon: "ai",
  },
  {
    id: "n4",
    type: "system",
    title: "New course available in your program",
    body: '"Advanced SQL for Analysts" has been added to your Data Literacy track.',
    time: "2 days ago",
    read: true,
    icon: "info",
  },
  {
    id: "n5",
    type: "social",
    title: "Carlos Mendez commented on your post",
    body: "Great insight on the leadership module discussion thread!",
    time: "3 days ago",
    read: true,
    icon: "message",
  },
  {
    id: "n6",
    type: "reminder",
    title: "Manager assigned a mandatory course",
    body: 'Your manager has assigned "ESG & Sustainability" — due in 30 days.',
    time: "4 days ago",
    read: true,
    icon: "alert",
  },
  {
    id: "n7",
    type: "achievement",
    title: "🔥 14-Day Learning Streak!",
    body: "You're on a 14-day streak! Keep going to earn the Consistent Learner badge.",
    time: "5 days ago",
    read: true,
    icon: "flame",
  },
];

export const COMPLETION_TREND = [
  { month: "Jul", completions: 342, enrollments: 580 },
  { month: "Aug", completions: 410, enrollments: 640 },
  { month: "Sep", completions: 380, enrollments: 590 },
  { month: "Oct", completions: 520, enrollments: 780 },
  { month: "Nov", completions: 490, enrollments: 730 },
  { month: "Dec", completions: 610, enrollments: 890 },
  { month: "Jan", completions: 680, enrollments: 950 },
];

export const DEPT_DATA = [
  { dept: "Engineering", completion: 84, learners: 312 },
  { dept: "Sales", completion: 71, learners: 245 },
  { dept: "HR", completion: 92, learners: 89 },
  { dept: "Finance", completion: 78, learners: 134 },
  { dept: "Marketing", completion: 67, learners: 178 },
  { dept: "Legal", completion: 95, learners: 62 },
  { dept: "Operations", completion: 75, learners: 228 },
];

export const SKILL_RADAR = [
  { skill: "Leadership", score: 72 },
  { skill: "Data Literacy", score: 58 },
  { skill: "Communication", score: 85 },
  { skill: "Technical", score: 64 },
  { skill: "Strategy", score: 70 },
  { skill: "Innovation", score: 53 },
];

export const PIE_DATA = [
  { name: "Video", value: 45, color: P.olive },
  { name: "Interactive", value: 28, color: P.gold },
  { name: "Reading", value: 17, color: P.sage },
  { name: "Assessment", value: 10, color: P.darkOlive },
];

export const QUIZ_QUESTIONS = [
  {
    q: "Which of the following best describes supervised machine learning?",
    options: [
      "The algorithm learns from labeled training data to make predictions",
      "The algorithm explores data patterns without any predefined labels",
      "The algorithm is rewarded or penalized based on actions taken",
      "The algorithm copies human decision-making processes exactly",
    ],
    correct: 0,
  },
  {
    q: "What is the primary purpose of a training-validation split in ML model development?",
    options: [
      "To reduce the size of the dataset for faster processing",
      "To detect and prevent overfitting on unseen data",
      "To increase the number of available features",
      "To ensure both datasets have equal class distribution",
    ],
    correct: 1,
  },
  {
    q: "Which metric is most appropriate for evaluating a classification model on an imbalanced dataset?",
    options: ["Accuracy", "Mean Squared Error", "F1 Score or AUC-ROC", "R-squared"],
    correct: 2,
  },
];

export const MONTHLY_LINE = [
  { month: "Jul", value: 62 },
  { month: "Aug", value: 68 },
  { month: "Sep", value: 65 },
  { month: "Oct", value: 73 },
  { month: "Nov", value: 71 },
  { month: "Dec", value: 78 },
  { month: "Jan", value: 75 },
];
