import { P } from "../../constants/theme.constants";

export const PROFILE_CERTS = [
  {
    id: "c1",
    course: "Cybersecurity Fundamentals & Compliance",
    issued: "Jan 12, 2025",
    expires: "Jan 12, 2027",
    score: 94,
    color: "#C0392B",
    hours: "4h",
    credId: "CER-2025-001-AM",
    expired: false,
  },
  {
    id: "c2",
    course: "Data-Driven Leadership",
    issued: "Dec 5, 2024",
    expires: "Dec 5, 2026",
    score: 88,
    color: P.darkOlive,
    hours: "6h",
    credId: "CER-2024-089-AM",
    expired: false,
  },
  {
    id: "c3",
    course: "Effective Communication in Remote Teams",
    issued: "Nov 18, 2024",
    expires: "Nov 18, 2026",
    score: 91,
    color: P.olive,
    hours: "4h",
    credId: "CER-2024-072-AM",
    expired: false,
  },
  {
    id: "c4",
    course: "GDPR Compliance Training 2023",
    issued: "Feb 15, 2023",
    expires: "Feb 15, 2024",
    score: 82,
    color: P.gold,
    hours: "3h",
    credId: "CER-2023-041-AM",
    expired: true,
  },
  {
    id: "c5",
    course: "Data Privacy Fundamentals 2022",
    issued: "Mar 10, 2022",
    expires: "Mar 10, 2023",
    score: 76,
    color: P.sage,
    hours: "2h",
    credId: "CER-2022-018-AM",
    expired: true,
  },
];

export const skills = [
  { name: "Software Engineering", level: 88, target: 95 },
  { name: "Data Literacy", level: 58, target: 80 },
  { name: "Leadership", level: 72, target: 85 },
  { name: "Communication", level: 85, target: 90 },
  { name: "Strategic Thinking", level: 63, target: 80 },
  { name: "AI & Innovation", level: 47, target: 75 },
];

export const quizAttemptHistory = [
  {
    quiz: "AI Foundations Assessment",
    course: "AI & Machine Learning for Business Leaders",
    date: "Jan 8, 2025",
    score: 87,
    attempt: 2,
    pass: true,
  },
  {
    quiz: "AI Foundations Assessment",
    course: "AI & Machine Learning for Business Leaders",
    date: "Jan 6, 2025",
    score: 62,
    attempt: 1,
    pass: false,
  },
  {
    quiz: "Cybersecurity Compliance Quiz",
    course: "Cybersecurity Fundamentals & Compliance",
    date: "Jan 4, 2025",
    score: 94,
    attempt: 1,
    pass: true,
  },
  {
    quiz: "Data Literacy Check",
    course: "Data-Driven Leadership & Decision Making",
    date: "Dec 20, 2024",
    score: 78,
    attempt: 2,
    pass: true,
  },
  {
    quiz: "Data Literacy Check",
    course: "Data-Driven Leadership & Decision Making",
    date: "Dec 18, 2024",
    score: 58,
    attempt: 1,
    pass: false,
  },
];
